[agent]
metrics_collection_interval = 60

[metrics]
namespace = "CWAgent"

  [metrics.append_dimensions]
  InstanceId = "${aws:InstanceId}"

  [metrics.metrics_collected.mem]
  measurement = ["used_percent", "total", "free"]

  [metrics.metrics_collected.disk]
  measurement = ["used_percent", "free", "total"]
  resources = ["/"]
